### ISSUE TITLE
Software Render ?

### ISSUE THREAD

**Issue by vertikalm** [Seenkao/New-ZenGL#3]
Hello,
Is it possible to use Zengl with rendering by software? Some Fallback?

**Comment by Seenkao** [comment]
Привет!
Нет, данная библиотека работает только с OpenGL. Версия ZenGL 3.12 может работать с DirectX.

Но в данной библиотеке предоставлена часть примитивов для общего использования. В следующей версии примитивов будет больше.
Если интересует, то смотрите **demo5**, там основная часть показана.

Google translate:
Hey!
No, this library only works with OpenGL. ZenGL version 3.12 can work with DirectX.

But this library provides some of the primitives for general use. There will be more primitives in the next version.
If interested, then see **demo5**, the main part is shown there.

**Comment by vertikalm** [comment]
Ok, thanks.
