### ISSUE TITLE
Example from Webassembly

### ISSUE THREAD

**Issue by Level0r0s** [Seenkao/New-ZenGL#5]
Is possible compiler example from webassembly ?

**Comment by Seenkao** [comment]
WebAssembly работает в браузере.
ZenGL сам создаёт окно и контекст для него. И ZenGL работает именно с этим окном.

Это разное. Потому нет. Примеров в данном варианте не планировалось.

----
Google translate:
WebAssembly runs in the browser.
ZenGL itself creates a window and a context for it. And ZenGL works with this window.

This is different. Therefore no. No examples were planned for this version.
