### ISSUE TITLE
New video decoder

### ISSUE THREAD

**Issue by GuvaCode** [Seenkao/New-ZenGL#6]
Привет Серж. Итересно можно ли прикрутить вот это https://github.com/astoeckel/acinerella
Я  в  raylib  успешно прикрутил без таймеров чисто голое видео. 
Хотел в zengl  попробовать но что-то голову сломал. Если интересно попробуй. 

PS. Добра и мира вам и вашим близким.

**Comment by Seenkao** [comment]
Привет!
Надо будет глянуть позже. На данное время занят. )))
